services:
  todo-frontend:
    image: eranikus424/todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
  todo-backend:
    image: eranikus424/todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend
    volumes:
      - todo-storage:/usr/src/app/storage
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - todo-frontend
      - todo-backend

volumes:
  todo-storage:
