### GET blogs
GET http://localhost:3001/api/blogs

### POST blog
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxQHRlc3QuY29tIiwiaWQiOjEsImlhdCI6MTcyNDkyMDI3OX0.XaMSfzTOEZaRNuKPn-lEUXk3gJfgnaRJX_sZgChTbbY

{
  "title": "Test",
  "author": "Test",
  "url": "Test",
  "likes": 0
}

### GET blog
GET http://localhost:3001/api/blogs/2

### PUT blog
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 5
}

### DELETE blog
DELETE http://localhost:3001/api/blogs/2
