services:
  example-frontend:
    build:
      context: ../../example-frontend
      dockerfile: Dockerfile
    container_name: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
  example-backend:
    build:
      context: ../../example-backend
      dockerfile: Dockerfile
    container_name: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=example
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
    container_name: redis
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
