apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: eranikus424/log-output
          volumeMounts:
            - name: log-output-volume
              mountPath: /usr/src/app/logs
          env:
            - name: PORT
              value: '3000'
            - name: PINGPONG_URL
              value: 'http://ping-pong-svc:1234/pingpong'
        - name: timestamp-generator
          image: eranikus424/timestamp-generator
          volumeMounts:
            - name: log-output-volume
              mountPath: /usr/src/app/logs
      volumes:
        - name: log-output-volume
          persistentVolumeClaim:
            claimName: log-output-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: eranikus424/ping-pong
          env:
            - name: PORT
              value: '3000'
