### login as root
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "secret"
}

### login with invalid credentials
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "invalid",
    "password": "invalid"
}