### GET todos
GET http://localhost:3000/api/todos

### POST todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "text": "test"
}

### PUT todo
PUT http://localhost:3000/api/todos/1
Content-Type: application/json

{
  "done": true
}