services:
  log-output:
    image: eranikus424/log-output
    build:
      context: ./log-output
      dockerfile: Dockerfile
    container_name: log-output
    environment:
      PINGPONG_URL: http://ping-pong:3000/pingpong
  timestamp-generator:
    image: eranikus424/timestamp-generator
    build:
      context: ./timestamp-generator
      dockerfile: Dockerfile
    container_name: timestamp-generator
  ping-pong:
    image: eranikus424/ping-pong
    build:
      context: ./ping-pong
      dockerfile: Dockerfile
    container_name: ping-pong
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: