### GET BMI with valid parameters
GET http://localhost:3003/bmi?height=180&weight=72

### GET BMI with invalid parameters
GET http://localhost:3003/bmi?height=invalid&weight=invalid

### GET BMI with no parameter
GET http://localhost:3003/bmi

### POST Exercises with valid parameters
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

### POST Exercises with invalid daily_exercises
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": "invalid",
  "target": 2
}

### POST Exercises with invalid target
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": "invalid"
}

### POST Exercises with no target
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

### POST Exercises with no parameters
POST http://localhost:3003/exercises
Content-Type: application/json
