### GET all blogs
GET http://localhost:3001/api/blogs/

### GET blog with id 1
GET http://localhost:3001/api/blogs/1

### POST new blog
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YjEwZGM5NmRjYWM0NzcyZmViZjgwNyIsImlhdCI6MTcyMjg4MzgxOCwiZXhwIjoxNzIyODg3NDE4fQ.a77n_4xvJGB1GX0xEL6fIt1tBqE4FU4dAbBNTJ0RpTM

{
    "title": "Blog Title",
    "author": "Author Name",
    "url": "http://localhost:3001/api/blogs/",
    "likes": 0
}

### POST without content
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

### PUT update blog
PUT http://localhost:3001/api/blogs/66ac8ca28626ea57fa4fc8f5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YjEwZGM5NmRjYWM0NzcyZmViZjgwNyIsImlhdCI6MTcyMjg4MzgxOCwiZXhwIjoxNzIyODg3NDE4fQ.a77n_4xvJGB1GX0xEL6fIt1tBqE4FU4dAbBNTJ0RpTM

{
    "title": "Update Blog Title",
    "author": "Update Author Name",
    "likes": 3
}

### PUT without content
PUT http://localhost:3001/api/blogs/66ac8ca28626ea57fa4fc8f5 HTTP/1.1
content-type: application/json

### DELETE blog with id 4
DELETE http://localhost:3001/api/blogs/4