### GET all blogs
GET http://localhost:3001/api/blogs/

### GET blog with id 1
GET http://localhost:3001/api/blogs/1

### POST new blog
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YjEwZGM5NmRjYWM0NzcyZmViZjgwNyIsImlhdCI6MTcyMjg4ODMxNH0.ikyj8B2uKW8CqPSvQblzNOCFnESiUprdwuvmPRsWnDk

{
    "title": "Blog Title",
    "author": "Author Name",
    "url": "http://localhost:3001/api/blogs/",
    "likes": 0
}

### POST without content
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

### PUT update blog
PUT http://localhost:3001/api/blogs/66ac8ca28626ea57fa4fc8f5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YjEwZGM5NmRjYWM0NzcyZmViZjgwNyIsImlhdCI6MTcyMjg4ODMxNH0.ikyj8B2uKW8CqPSvQblzNOCFnESiUprdwuvmPRsWnDk

{
    "title": "Update Blog Title",
    "author": "Update Author Name",
    "likes": 3
}

### PUT without content
PUT http://localhost:3001/api/blogs/66ac8ca28626ea57fa4fc8f5 HTTP/1.1
content-type: application/json

### DELETE blog with id 66b1201c0db2424c7533db76
DELETE http://localhost:3001/api/blogs/66b1201c0db2424c7533db76
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjZiMTA3NGY1MWQ2NjNlYWUzM2I0NmViIiwiaWF0IjoxNzIyODg4NTU3fQ.paqTBIs5irgCtp4xKtJr-9xxHS-G4KOe6UXrP8cMAvs

### GET blog comments
GET http://localhost:3001/api/blogs/66b36fb613ede074cbf98da7/comments

### POST new comment
POST http://localhost:3001/api/blogs/66b36fb613ede074cbf98da7/comments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjZiMTA3NGY1MWQ2NjNlYWUzM2I0NmViIiwiaWF0IjoxNzIyODg4NTU3fQ.paqTBIs5irgCtp4xKtJr-9xxHS-G4KOe6UXrP8cMAvs

{
    "comment": "New comment"
}