FROM golang:1.16.15-alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build

RUN adduser -D appuser
RUN chown appuser .

USER appuser

CMD ["./server"]