FROM node:16-alpine3.18

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN npm install

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN npm run build

RUN npm install -g serve

RUN adduser -D appuser
RUN chown appuser .

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]