apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo
  name: hourly-todo-cronjob
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hourly-todo
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - |
                  WIKI_URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i ^location | cut -d' ' -f2 | sed 's/\r//');
                  PAYLOAD=$(printf '{"text":"Read %s"}' "$WIKI_URL");
                  echo "Sending payload: $PAYLOAD";
                  RESPONSE=$(curl -s -X POST ${TODO_BACKEND_URL} -H "Content-Type: application/json" -d "$PAYLOAD");
                  echo "Response from server: $RESPONSE";
              env:
                - name: TODO_BACKEND_URL
                  value: http://todo-backend-svc:2345/api/todos
          restartPolicy: OnFailure
