apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo
  name: todo-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: gcr.io/dwk-gke-24/todo-frontend
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo
  name: todo-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  # GKE doesn't support ReadWriteMany for pvc, so we use Recreate for deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: gcr.io/dwk-gke-24/todo-backend
          imagePullPolicy: Always
          volumeMounts:
            - name: todo-volume
              mountPath: /usr/src/app/storage
          env:
            - name: PORT
              value: '3000'
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_url
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: todo-volume
          persistentVolumeClaim:
            claimName: todo-pvc
