apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: todo-pvc
spec:
  storageClassName: todo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
