### GET info
GET http://localhost:3001/info/

### GET all persons
GET http://localhost:3001/api/persons/

### GET person with id 66aca82b7843ef0433909c65
GET http://localhost:3001/api/persons/66aca82b7843ef0433909c65

### GET person with invalid id
GET http://localhost:3001/api/persons/invalid

### POST new person
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Test Person",
    "number": "123-456789"
}

### POST with duplicated name
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "123-456789"
}

### POST without name
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "123-456789"
}

### POST without number
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Test without Number"
}

### POST without content
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

### PUT update person
PUT http://localhost:3001/api/persons/66aca82b7843ef0433909c65 HTTP/1.1
content-type: application/json

{
    "name": "Test Person",
    "number": "123-456789"
}

### PUT with invalid content
PUT http://localhost:3001/api/persons/66aca82b7843ef0433909c65 HTTP/1.1
content-type: application/json

{
    "name": "aa"
}

### PUT without content
PUT http://localhost:3001/api/persons/66aca82b7843ef0433909c65 HTTP/1.1
content-type: application/json

### DELETE person with id 3
DELETE http://localhost:3001/api/persons/3
