services:
  example-frontend:
    build:
      context: ../../example-frontend
      dockerfile: exercise.2.9.Dockerfile
    container_name: example-frontend
  example-backend:
    build:
      context: ../../example-backend
      dockerfile: exercise.2.9.Dockerfile
    container_name: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=example
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
    container_name: redis
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - example-frontend
      - example-backend

volumes:
  database:
