name: Release Node.js app

on:
  push:
    branches:
      - main
    paths:
      - 'docker/part3/express-app/**'
      - '.github/workflows/docker-express-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/part3/express-app
          push: true
          tags: eranikus424/express-app:latest
