name: Automatic delete todo-app from GKE

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: asia-east2-a
  BRANCH: ${{ github.event.ref }}

jobs:
  delete-todo-gke:
    name: Delete todo-app from GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Delete environment
        run: |-
          cd kubernetes/todo-app/

          NAMESPACE=todo
          if [[ ${BRANCH} != 'main' ]]
          then
            NAMESPACE=${NAMESPACE}-${BRANCH}
          fi
          echo "Delete ${BRANCH} branch from namespace ${NAMESPACE}"
          kubectl config set-context --current --namespace=${NAMESPACE}
          kustomize edit set namespace ${NAMESPACE}

          kustomize build . | kubectl delete -f - || true

          kubectl get all -o wide
